title: "The 42 t"
description: Fancy description
google_analytics: 
show_downloads: false
remote_theme: benbalter/retlab
nav_pages:
  - index.html
  - md.md
footer_pages:
  - footer.md
  - md.md

gems:
  - jekyll-mentions
